# 设置服务器端口
server:
  port: 8080

# 开发环境数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ************************************************************
    username: *********************************************************
    password: *********************************************************
  data:
    # redis配置
    redis:
      host: localhost
      port: 6379
    # mongodb配置
    mongodb:
      uri: ************************************************************
      database: ***************************************

# 生产环境配置
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: ************************************************
#    username: *************************************************
#    password: *************************************************
#  data:
#    # redis配置
#    redis:
#      host: localhost
#      port: 6379
#      password: ***************************************
#    # mongodb配置
#    mongodb:
#      uri: ***********************************************************************
#      database: ******************************************************************


# mybatis配置
mybatis:
  mapper-locations: classpath:dao/*.xml                      # 扫描dao .xml
  type-aliases-package: com.easyshare.pojo                   # 设置实体类别名
  configuration:
    cache-enabled: true                                      # 开启缓存
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl    # 打印sql日志

#阿里云OSS配置信息
aliyun:
  oss:
    endpoint: *************************************
    accessKeyId: *****************************************
    accessKeySecret: ******************************************
    bucketName: **********************************

# socketio配置
socketio:
  host: 0.0.0.0
  port: 9999
  maxFramePayloadLength: 1048576   # 设置最大每帧处理数据的长度，防止他人利用大数据来攻击服务器
  maxHttpContentLength: 1048576    # 设置http交互最大内容长度
  bossCount: 1                     # socket连接数大小（如只监听一个端口boss线程组为1即可）
  workCount: 100
  allowCustomRequests: true
  upgradeTimeout: 1000000          # 协议升级超时时间（毫秒），默认10秒。HTTP握手升级为ws协议超时时间
  pingTimeout: 6000000             # Ping消息超时时间（毫秒），默认60秒，这个时间间隔内没有接收到心跳消息就会发送超时事件
  pingInterval: 25000              # Ping消息超时时间（毫秒），默认60秒，这个时间间隔内没有接收到心跳消息就会发送超时事件

# 日志设置
logging:
  level:
    com.easyshare.listener: trace

